services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      NS_MARIADB_HOSTNAME: mariadb
      NS_MARIADB_PORT: 3306
      NS_MARIADB_USER: user
      NS_MARIADB_PASSWORD: password
      NS_MARIADB_DATABASE: template_db
      JWT_SECRET: b6b6424fbcf066b80d45b454e677f730097279e6d2bd5ab6
    volumes:
      - .:/app
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: template_db
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mariadb_data:
