openapi: 3.0.0
info:
  title: Kaitoyama Server API
  version: "1.0.0"
servers:
  - url: 'http://localhost:8080/api'
    description: ローカル環境
  - url: 'https://YOUR_PRODUCTION_URL'
    description: 本番環境
paths:
  /health:
    get:
      summary: Health check endpoint
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "ok"
