// Package models provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package models

// Defines values for PostRoomsActionsJSONBodyAction.
const (
	CANCEL PostRoomsActionsJSONBodyAction = "CANCEL"
	JOIN   PostRoomsActionsJSONBodyAction = "JOIN"
	READY  PostRoomsActionsJSONBodyAction = "READY"
	START  PostRoomsActionsJSONBodyAction = "START"
)

// Room defines model for Room.
type Room struct {
	IsOpened bool     `json:"isOpened"`
	RoomId   int      `json:"roomId"`
	RoomName string   `json:"roomName"`
	Users    []string `json:"users"`
}

// UserCreate defines model for UserCreate.
type UserCreate struct {
	// Password SHA256 hashed password
	Password string `json:"password"`
	Username string `json:"username"`
}

// PostRoomsActionsJSONBody defines parameters for PostRoomsActions.
type PostRoomsActionsJSONBody struct {
	Action PostRoomsActionsJSONBodyAction `json:"action"`
}

// PostRoomsActionsJSONBodyAction defines parameters for PostRoomsActions.
type PostRoomsActionsJSONBodyAction string

// PostRoomsActionsJSONRequestBody defines body for PostRoomsActions for application/json ContentType.
type PostRoomsActionsJSONRequestBody PostRoomsActionsJSONBody

// PostUsersJSONRequestBody defines body for PostUsers for application/json ContentType.
type PostUsersJSONRequestBody = UserCreate
