// Package models provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package models

// Defines values for PostRoomsActionsJSONBodyAction.
const (
	CANCEL PostRoomsActionsJSONBodyAction = "CANCEL"
	JOIN   PostRoomsActionsJSONBodyAction = "JOIN"
	READY  PostRoomsActionsJSONBodyAction = "READY"
	START  PostRoomsActionsJSONBodyAction = "START"
)

// Board defines model for Board.
type Board struct {
	Content   []int `json:"content"`
	GainScore int   `json:"gainScore"`

	// Version The new version of the board state
	Version int `json:"version"`
}

// Room defines model for Room.
type Room struct {
	IsOpened bool     `json:"isOpened"`
	RoomId   int      `json:"roomId"`
	RoomName string   `json:"roomName"`
	Users    []string `json:"users"`
}

// RoomResultItem defines model for RoomResultItem.
type RoomResultItem struct {
	Score int `json:"score"`

	// User username
	User string `json:"user"`
}

// UserCreate defines model for UserCreate.
type UserCreate struct {
	// Password SHA256 hashed password
	Password string `json:"password"`
	Username string `json:"username"`
}

// PostRoomsActionsJSONBody defines parameters for PostRoomsActions.
type PostRoomsActionsJSONBody struct {
	Action PostRoomsActionsJSONBodyAction `json:"action"`
}

// PostRoomsActionsJSONBodyAction defines parameters for PostRoomsActions.
type PostRoomsActionsJSONBodyAction string

// PostRoomsFormulasJSONBody defines parameters for PostRoomsFormulas.
type PostRoomsFormulasJSONBody struct {
	Formula string `json:"formula"`
}

// PostRoomsActionsJSONRequestBody defines body for PostRoomsActions for application/json ContentType.
type PostRoomsActionsJSONRequestBody PostRoomsActionsJSONBody

// PostRoomsFormulasJSONRequestBody defines body for PostRoomsFormulas for application/json ContentType.
type PostRoomsFormulasJSONRequestBody PostRoomsFormulasJSONBody

// PostUsersJSONRequestBody defines body for PostUsers for application/json ContentType.
type PostUsersJSONRequestBody = UserCreate
